const axios = require('axios')

let data = {
    verb : 'PUT',
    endpoint : 'https://guesty-user-service.herokuapp.com/user/{userId}',
    payloads:[{
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            age:30
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            email:"a@gmail.com"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    },
    {
        userId:'ja2S-hs81-ksn3-iQI9',
        data:{
            name:"roni"
        }
    }]
}
axios.post('http://localhost:3000/batch', data).then(res=>{
    console.log(res.data)
}).catch(err=>
    console.log(err))

axios.post('http://localhost:3000/batch', data).then(res=>{
    console.log(res.data)
}).catch(err=>
    console.log(err))